// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7T7TEru7MbwUgIdbUsAT0dForoeUNNjQ',
    appId: '1:401685867250:web:e1da6431bb0a719824fe6b',
    messagingSenderId: '401685867250',
    projectId: 'mad-exam-project',
    authDomain: 'mad-exam-project.firebaseapp.com',
    storageBucket: 'mad-exam-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnYjEXNGS_Q4YxD4vxYc9f2hxiWBi_rU',
    appId: '1:401685867250:android:3251a3af2b65b6f024fe6b',
    messagingSenderId: '401685867250',
    projectId: 'mad-exam-project',
    storageBucket: 'mad-exam-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmv-XA3f1hKIJf1FfJUBVPsQmD9qkKlSE',
    appId: '1:401685867250:ios:890d32c98b02f33524fe6b',
    messagingSenderId: '401685867250',
    projectId: 'mad-exam-project',
    storageBucket: 'mad-exam-project.firebasestorage.app',
    iosBundleId: 'com.example.madExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmv-XA3f1hKIJf1FfJUBVPsQmD9qkKlSE',
    appId: '1:401685867250:ios:890d32c98b02f33524fe6b',
    messagingSenderId: '401685867250',
    projectId: 'mad-exam-project',
    storageBucket: 'mad-exam-project.firebasestorage.app',
    iosBundleId: 'com.example.madExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7T7TEru7MbwUgIdbUsAT0dForoeUNNjQ',
    appId: '1:401685867250:web:4964cb9d56a2f89624fe6b',
    messagingSenderId: '401685867250',
    projectId: 'mad-exam-project',
    authDomain: 'mad-exam-project.firebaseapp.com',
    storageBucket: 'mad-exam-project.firebasestorage.app',
  );
}
